// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwnpfzldlwsopdljoope.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bnBmemxkbHdzb3BkbGpvb3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTYyMzMsImV4cCI6MjA2MzQ3MjIzM30.m5gZl_0JATnj2-mzwtMIn3FVt6f5F44hLfZaw_YABV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);